export const iconPacks = [
	{
		name: "Tabler Icons",
		cdnId: "tabler",
		website: "https://tabler.io/icons",
		github: "https://github.com/tabler/tabler-icons",
		licenseUrl: "[github]/blob/main/LICENSE",
		license: "MIT",
	},
	{
		name: "Feather Icons",
		cdnId: "feather",
		website: "https://feathericons.com/",
		github: "https://github.com/feathericons/feather",
		licenseUrl: "[github]/blob/main/LICENSE",
		license: "MIT",
	},
	{
		name: "Lucide Icons",
		cdnId: "lucide",
		website: "https://lucide.dev",
		github: "https://github.com/lucide-icons/lucide",
		licenseUrl: "[github]/blob/main/LICENSE",
		license: "ISC",
	},
	{
		name: "Heroicons",
		cdnId: "heroicons",
		website: "https://heroicons.com/",
		github: "https://github.com/tailwindlabs/heroicons",
		licenseUrl: "[github]/blob/master/LICENSE",
		license: "MIT",
	},
	{
		name: "Material Icons",
		cdnId: "ic",
		website: "https://fonts.google.com/icons",
		github: "https://github.com/google/material-design-icons",
		licenseUrl: "[github]/blob/master/LICENSE",
		license: "Apache-2.0",
	},
	{
		name: "Bootstrap Icons",
		cdnId: "bi",
		website: "https://icons.getbootstrap.com/",
		github: "https://github.com/twbs/icons",
		licenseUrl: "[github]/blob/main/LICENSE",
		license: "MIT",
	},
	{
		name: "BoxIcons",
		cdnId: "bx",
		website: "https://boxicons.com/",
		github: "https://github.com/atisawd/boxicons",
		licenseUrl: "[github]/blob/master/LICENSE",
		license: "MIT",
	},
	{
		name: "Majesticons",
		cdnId: "majesticons",
		website: "https://www.majesticons.com/",
		github: "https://github.com/halfmage/majesticons",
		licenseUrl: "[github]/blob/main/LICENSE",
		license: "MIT",
	},
	{
		name: "Circum Icons",
		cdnId: "circum",
		website: "https://circumicons.com/",
		github: "https://github.com/Klarr-Agency/Circum-icons",
		licenseUrl: "[github]/blob/main/LICENSE",
		license: "MIT",
	},
	{
		name: "Radix Icons",
		cdnId: "radix-icons",
		website: "https://www.radix-ui.com/icons",
		github: "https://github.com/radix-ui/icons",
		licenseUrl: "[github]/blob/master/LICENSE",
		license: "MIT",
	},
	{
		name: "Carbon Icons",
		cdnId: "carbon",
		website: "https://carbondesignsystem.com/elements/icons/library/",
		github: "https://github.com/carbon-design-system/carbon-icons",
		licenseUrl: "[github]/blob/master/LICENSE",
		license: "Apache-2.0",
	},
	{
		name: "Streamline",
		cdnId: "streamline",
		website: "https://www.streamlinehq.com/?tab=free",
	},
	{
		name: "css.gg",
		cdnId: "gg",
		website: "https://css.gg/",
		github: "https://github.com/astrit/css.gg",
		licenseUrl: "[github]/blob/master/LICENSE",
		license: "MIT",
	},
	{
		name: "Eva Icons",
		cdnId: "eva",
		website: "https://akveo.github.io/eva-icons/#/",
		github: "https://github.com/akveo/eva-icons",
		licenseUrl: "[github]/blob/master/LICENSE",
		license: "MIT",
	},
	{
		name: "Gridicons",
		cdnId: "gridicons",
		website: "https://automattic.github.io/gridicons/",
		github: "https://github.com/Automattic/gridicons",
		licenseUrl: "[github]/blob/trunk/LICENSE",
		license: "GPL-2.0",
	},
	{
		name: "Akar Icons",
		cdnId: "akar-icons",
		website: "https://akaricons.com/",
		github: "https://github.com/artcoholic/akar-icons",
		licenseUrl: "[github]/blob/master/LICENSE",
		license: "MIT",
	},
	{
		name: "Ant Design Icons",
		cdnId: "ant-design",
		website: "https://ant.design/components/icon",
		github: "https://github.com/ant-design/ant-design-icons",
		licenseUrl: "[github]/blob/master/LICENSE",
		license: "MIT",
	},
	{
		name: "Basil Icons",
		cdnId: "basil",
		website: "https://craftwork.design/downloads/basil/",
	},
	{
		name: "Remix Icon",
		cdnId: "ri",
		website: "https://remixicon.com/",
		github: "https://github.com/Remix-Design/RemixIcon",
		licenseUrl: "[github]/blob/master/LICENSE",
		license: "Apache-2.0",
	},
	{
		name: "Octicons",
		cdnId: "octicon",
		website: "https://primer.style/foundations/icons",
		github: "https://github.com/primer/octicons",
		licenseUrl: "[github]/blob/main/LICENSE",
		license: "MIT",
	},
	{
		name: "Fluent UI Icons",
		cdnId: "fluent",
		github: "https://github.com/microsoft/fluentui-system-icons",
		licenseUrl: "[github]/blob/main/LICENSE",
		license: "MIT",
	},
	{
		name: "Ionicons",
		cdnId: "ion",
		website: "https://ionic.io/ionicons",
		github: "https://github.com/ionic-team/ionicons",
		licenseUrl: "[github]/blob/main/LICENSE",
		license: "MIT",
	},
	{
		name: "Jam Icons",
		cdnId: "jam",
		website: "https://jam-icons.com/",
		github: "https://github.com/michaelampr/jam",
		licenseUrl: "[github]/blob/master/LICENSE",
		license: "MIT",
	},
	{
		name: "Simple Icons",
		cdnId: "simple-icons",
		website: "https://simpleicons.org/",
		github: "https://github.com/simple-icons/simple-icons",
		licenseUrl: "[github]/blob/develop/LICENSE",
		license: "CC0-1.0",
	},
	{
		name: "Iconoir",
		cdnId: "iconoir",
		website: "https://iconoir.com/",
		github: "https://github.com/iconoir-icons/iconoir",
		licenseUrl: "[github]/blob/main/LICENSE",
		license: "MIT",
	},
	{
		name: "Pixelarticons",
		cdnId: "pixelarticons",
		website: "https://pixelarticons.com/",
		github: "https://github.com/halfmage/pixelarticons",
		licenseUrl: "[github]/blob/master/LICENSE",
		license: "MIT",
	},
	{
		name: "Game Icons",
		cdnId: "game-icons",
		website: "https://game-icons.net/",
		github: "https://github.com/game-icons/icons",
		licenseUrl: "[github]/blob/master/license.txt",
		license: "CC-BY 3.0 / CC0",
	},
];
