export const ControlType = {
	Boolean: "boolean",
	Number: "number",
	String: "string",
	RichText: "richtext",
	FusedNumber: "fusednumber",
	Enum: "enum",
	SegmentedEnum: "segmentedenum",
	Color: "color",
	Image: "image",
	ResponsiveImage: "responsiveimage",
	File: "file",
	ComponentInstance: "componentinstance",
	Array: "array",
	EventHandler: "eventhandler",
	Transition: "transition",
	BoxShadow: "boxshadow",
	Link: "link",
	Date: "date",
	Object: "object",
	Font: "font",
	PageScope: "pagescope",
	ScrollSectionRef: "scrollsectionref",
	CustomCursor: "customcursor",
	Border: "border",
	Cursor: "cursor",
};
