#:schema node_modules/wrangler/config-schema.json
name = "framersync-workers"
main = "src/index.ts"
compatibility_date = "2024-08-06"
node_compat = true

kv_namespaces = [
  { binding = "keyValueStore", id = "a869bdc0e9a24b50b8874e01203fa449" }
]

[vars]
NOTION_CLIENT_ID = "c213633a-8eee-47e0-b126-6a25b2d5a622"
AIRTABLE_CLIENT_ID = "da5fb6c7-a40e-4931-8f06-67507c3816eb"
GOOGLE_APP_ID = "830588332904"
GOOGLE_CLIENT_ID = "830588332904-7i1eb1jjv2ped73sniikp1od2d9ri0vl.apps.googleusercontent.com"
PLUGIN_URI = "https://plugin.framersync.com"
REDIRECT_URI = "https://framersync-workers.isaac-b49.workers.dev"

[observability]
enabled = true
head_sampling_rate = 1
